import {
	type TournamentMatch,
	type TournamentSeed,
	type MatchRecord,
	type Player,
} from '@badminton/types';
import { computePlayerStats } from '../statistics/player-stats';

/**
 * Seed players by win rate (descending) for singles.
 * Players with no matches get lowest seeds.
 */
export function seedPlayers(players: Player[], matchRecords: MatchRecord[]): TournamentSeed[] {
	const statsMap = new Map<string, { winRate: number; wins: number }>();
	for (const p of players) {
		const stats = computePlayerStats(p.id, matchRecords);
		statsMap.set(p.id, { winRate: stats.winRate, wins: stats.wins });
	}

	const sorted = [...players].sort((a, b) => {
		const sa = statsMap.get(a.id)!;
		const sb = statsMap.get(b.id)!;
		return sb.winRate - sa.winRate || sb.wins - sa.wins;
	});

	return sorted.map((p, i) => ({
		playerId: p.id,
		seedNumber: i + 1,
	}));
}

/**
 * Pair players into balanced doubles teams (best+worst, 2nd+2nd-worst, etc.).
 * Returns teams as { id, playerIds } where id is generated by the caller.
 */
export function pairTeamsBalanced(
	players: Player[],
	matchRecords: MatchRecord[],
	idGenerator: () => string,
): { id: string; playerIds: string[] }[] {
	const statsMap = new Map<string, { winRate: number; wins: number }>();
	for (const p of players) {
		const stats = computePlayerStats(p.id, matchRecords);
		statsMap.set(p.id, { winRate: stats.winRate, wins: stats.wins });
	}

	const sorted = [...players].sort((a, b) => {
		const sa = statsMap.get(a.id)!;
		const sb = statsMap.get(b.id)!;
		return sb.winRate - sa.winRate || sb.wins - sa.wins;
	});

	const teams: { id: string; playerIds: string[] }[] = [];
	const n = sorted.length;
	for (let i = 0; i < n / 2; i++) {
		teams.push({
			id: idGenerator(),
			playerIds: [sorted[i].id, sorted[n - 1 - i].id],
		});
	}

	return teams;
}

/**
 * Seed doubles teams by average win rate (descending).
 */
export function seedTeams(
	teams: { id: string; playerIds: string[] }[],
	matchRecords: MatchRecord[],
): TournamentSeed[] {
	const teamStats = teams.map((team) => {
		let totalWinRate = 0;
		for (const pid of team.playerIds) {
			const stats = computePlayerStats(pid, matchRecords);
			totalWinRate += stats.winRate;
		}
		return {
			id: team.id,
			avgWinRate: totalWinRate / team.playerIds.length,
		};
	});

	teamStats.sort((a, b) => b.avgWinRate - a.avgWinRate);

	return teamStats.map((t, i) => ({
		playerId: t.id,
		seedNumber: i + 1,
	}));
}

/**
 * Pad seeds to next power of 2 for bracket generation.
 */
function padToNextPow2(seeds: TournamentSeed[]): (TournamentSeed | null)[] {
	let size = 1;
	while (size < seeds.length) size *= 2;
	const padded: (TournamentSeed | null)[] = [...seeds];
	while (padded.length < size) padded.push(null);
	return padded;
}

/**
 * Standard bracket seeding order for power-of-2 bracket.
 * E.g., for 8 players: [1,8,4,5,2,7,3,6]
 */
function bracketOrder(n: number): number[] {
	if (n === 1) return [0];
	const half = bracketOrder(n / 2);
	const result: number[] = [];
	for (const h of half) {
		result.push(h);
		result.push(n - 1 - h);
	}
	return result;
}

/**
 * Generate an elimination bracket from seeds.
 * Works for both singles and doubles — the seed's playerId
 * is either a player ID (singles) or a team ID (doubles).
 */
export function generateBracket(
	seeds: TournamentSeed[],
	idGenerator: () => string,
): TournamentMatch[] {
	const padded = padToNextPow2(seeds);
	const n = padded.length;
	const order = bracketOrder(n);
	const ordered = order.map((i) => padded[i] ?? null);

	const matches: TournamentMatch[] = [];
	const totalRounds = Math.log2(n);

	// Round 1 matches
	for (let i = 0; i < n / 2; i++) {
		const a = ordered[i * 2];
		const b = ordered[i * 2 + 1];

		const match: TournamentMatch = {
			id: idGenerator(),
			round: 1,
			position: i,
			playerA: a?.playerId,
			playerB: b?.playerId,
			status: 'pending',
		};

		// If one player is a bye (null), auto-advance the other
		if (a && !b) {
			match.winner = a.playerId;
			match.status = 'completed';
		} else if (!a && b) {
			match.winner = b.playerId;
			match.status = 'completed';
		} else if (a && b) {
			match.status = 'ready';
		}

		matches.push(match);
	}

	// Later rounds (empty placeholders)
	for (let round = 2; round <= totalRounds; round++) {
		const matchesInRound = n / Math.pow(2, round);
		for (let pos = 0; pos < matchesInRound; pos++) {
			matches.push({
				id: idGenerator(),
				round,
				position: pos,
				status: 'pending',
			});
		}
	}

	// Propagate byes forward
	return propagateByes(matches, totalRounds);
}

// Keep old name as alias for backwards compatibility
export const generateSingleEliminationBracket = generateBracket;

/**
 * Generate an elimination bracket from explicit Round 1 matchups.
 * Used when the admin manually selects who plays against who.
 *
 * @param matchups - Pairs of participant IDs for Round 1 matches
 * @param byeParticipants - Participant IDs that get a bye in Round 1
 * @param idGenerator - UUID generator
 */
export function generateBracketManual(
	matchups: [string, string][],
	byeParticipants: string[],
	idGenerator: () => string,
): TournamentMatch[] {
	// Total slots needed = (matchups * 2) + byes, padded to next power of 2
	const totalParticipants = matchups.length * 2 + byeParticipants.length;
	let bracketSize = 1;
	while (bracketSize < totalParticipants) bracketSize *= 2;

	const totalByes = bracketSize - totalParticipants + byeParticipants.length;
	const totalRounds = Math.log2(bracketSize);
	const firstRoundMatchCount = bracketSize / 2;

	const matches: TournamentMatch[] = [];

	// Build Round 1: interleave real matches and bye matches
	let matchupIdx = 0;
	let byeIdx = 0;
	// Track which explicit bye participants we've placed
	const explicitByes = [...byeParticipants];
	// Remaining byes are empty (null vs null) to pad bracket
	const paddingByes = totalByes - explicitByes.length;

	for (let pos = 0; pos < firstRoundMatchCount; pos++) {
		if (matchupIdx < matchups.length) {
			// Place a real match
			const [a, b] = matchups[matchupIdx++];
			matches.push({
				id: idGenerator(),
				round: 1,
				position: pos,
				playerA: a,
				playerB: b,
				status: 'ready',
			});
		} else if (byeIdx < explicitByes.length) {
			// Bye participant — auto-advances
			const participant = explicitByes[byeIdx++];
			matches.push({
				id: idGenerator(),
				round: 1,
				position: pos,
				playerA: participant,
				status: 'completed',
				winner: participant,
			});
		} else {
			// Padding bye (empty slot)
			matches.push({
				id: idGenerator(),
				round: 1,
				position: pos,
				status: 'completed',
			});
		}
	}

	// Later rounds (empty placeholders)
	for (let round = 2; round <= totalRounds; round++) {
		const matchesInRound = bracketSize / Math.pow(2, round);
		for (let pos = 0; pos < matchesInRound; pos++) {
			matches.push({
				id: idGenerator(),
				round,
				position: pos,
				status: 'pending',
			});
		}
	}

	// Propagate byes forward
	return propagateByes(matches, totalRounds);
}

/** Check if a match is a padding bye (empty completed match with no participants). */
function isPaddingBye(match: TournamentMatch): boolean {
	return match.status === 'completed' && !match.winner && !match.playerA && !match.playerB;
}

/**
 * After initial bracket generation, propagate bye winners forward.
 * Also auto-advances participants whose opponent side is a padding bye.
 */
function propagateByes(matches: TournamentMatch[], totalRounds: number): TournamentMatch[] {
	const result = [...matches];

	for (let round = 1; round < totalRounds; round++) {
		const currentRoundMatches = result.filter((m) => m.round === round);
		const nextRoundMatches = result.filter((m) => m.round === round + 1);

		for (const match of currentRoundMatches) {
			if (match.winner && match.status === 'completed') {
				const nextPos = Math.floor(match.position / 2);
				const nextMatch = nextRoundMatches.find((m) => m.position === nextPos);
				if (nextMatch) {
					if (match.position % 2 === 0) {
						nextMatch.playerA = match.winner;
					} else {
						nextMatch.playerB = match.winner;
					}
					if (nextMatch.playerA && nextMatch.playerB) {
						nextMatch.status = 'ready';
					}
				}
			}
		}

		// Auto-advance through padding byes: if a next-round match has exactly
		// one participant and the other side comes from a padding bye, auto-advance.
		for (const nextMatch of nextRoundMatches) {
			if (nextMatch.status === 'completed' || nextMatch.status === 'ready') continue;
			if ((!nextMatch.playerA && !nextMatch.playerB) || (nextMatch.playerA && nextMatch.playerB)) continue;

			const participant = nextMatch.playerA || nextMatch.playerB;
			const missingIsB = !nextMatch.playerB;
			const feederPos = missingIsB ? nextMatch.position * 2 + 1 : nextMatch.position * 2;
			const feeder = currentRoundMatches.find((m) => m.position === feederPos);

			if (feeder && isPaddingBye(feeder)) {
				nextMatch.winner = participant;
				nextMatch.status = 'completed';
			}
		}
	}

	return result;
}

/**
 * Advance a winner in the bracket and update subsequent matches.
 * Auto-advances through padding byes (empty bracket slots).
 */
export function advanceWinner(
	matches: TournamentMatch[],
	matchId: string,
	winnerId: string,
	scoreA?: number,
	scoreB?: number,
): TournamentMatch[] {
	const result = matches.map((m) => ({ ...m }));
	const match = result.find((m) => m.id === matchId);
	if (!match) return result;

	match.winner = winnerId;
	match.scoreA = scoreA;
	match.scoreB = scoreB;
	match.status = 'completed';

	// Propagate winner forward, auto-advancing through padding byes
	let currentRound = match.round;
	let currentPos = match.position;
	let currentWinner = winnerId;

	while (true) {
		const nextRoundMatches = result.filter((m) => m.round === currentRound + 1);
		const nextPos = Math.floor(currentPos / 2);
		const nextMatch = nextRoundMatches.find((m) => m.position === nextPos);
		if (!nextMatch) break;

		if (currentPos % 2 === 0) {
			nextMatch.playerA = currentWinner;
		} else {
			nextMatch.playerB = currentWinner;
		}

		if (nextMatch.playerA && nextMatch.playerB) {
			nextMatch.status = 'ready';
			break;
		}

		// Check if the other feeder is a padding bye
		const otherFeederPos = currentPos % 2 === 0 ? currentPos + 1 : currentPos - 1;
		const otherFeeder = result.find(
			(m) => m.round === currentRound && m.position === otherFeederPos,
		);

		if (otherFeeder && isPaddingBye(otherFeeder)) {
			// No opponent coming — auto-advance through this round
			nextMatch.winner = currentWinner;
			nextMatch.status = 'completed';
			currentRound = nextMatch.round;
			currentPos = nextMatch.position;
		} else {
			break;
		}
	}

	return result;
}

/**
 * Check if a tournament is complete.
 */
export function isTournamentComplete(matches: TournamentMatch[]): boolean {
	return matches.every((m) => m.status === 'completed');
}

/**
 * Get the winner of a completed tournament.
 */
export function getTournamentWinner(matches: TournamentMatch[]): string | undefined {
	if (!isTournamentComplete(matches)) return undefined;
	const maxRound = Math.max(...matches.map((m) => m.round));
	const finalMatch = matches.find((m) => m.round === maxRound && m.position === 0);
	return finalMatch?.winner;
}
